version: '3.8'
services:
  weaviate:
    image: semitechnologies/weaviate:1.27.10
    restart: on-failure:0
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./weaviate_data"
      QUERY_DEFAULTS_LIMIT: 25
      DEFAULT_VECTORIZER_MODULE: "none"
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:
